### PR TITLE
Packaging updates - failed trades send zero material and more robust GetFillMass 

### LINKED ISSUE #1785: Package-related "failed" trades cause seg faults
In #1749, we dealt with the reality that sometimes an agent with material sell policy would make a bid of material that could be packaged, and the requesting agent would accept a smaller amount of material (for example, if they were able to get their request partially filled with a higher preference material from another agent). Then, the DRE would execute the trade and suddenly the agent would be faced with a trade it couldn't make. E.g. request for 2 kg. Bid for 2 kg with packaging requirements of 2 kg. Requester ultimately accepts 1 kg. When trying to execute the trade, can't package 1 kg, so sends an empty trade back

I thought this "failed" trade could just be sent with no material.  Turns out, this actually seg faults. 

Possible solutions:
- Change how trades work so that zero trades ("failed" trades) can go through and be accepted
- Make all packaged trades (anything not using `unpackaged`) exclusive

### PR DESCRIPTION
**Pull request by nuclearkatie**
Addresses @gonuke's comments on [cycamore#621](https://github.com/cyclus/cycamore/pull/621)

Closes #1785 and is part of process for addressing #1786

### CODE REVIEW

**Comment by nuclearkatie** [comment]
After several re-runs, still getting failures on two of the three conda runs (but not 20.04)... don't really know why

File: src/package.cc [hunk 1]
```diff
@@ -49,7 +51,13 @@ double Package::GetFillMass(double qty) {
       fill_mass = fill_max_;
     }
   }
-  return std::min(qty, fill_mass);
+  fill_mass = std::min(qty, fill_mass);
+  if (fill_mass >= fill_min_) {
```
Comment (gonuke) [inline src/package.cc:55]: I think by returning this pair, you may not even need this test anymore, at all, because you've removed the pathological case.  It used to be possible to return `GetFillMass() = 0` because of the early return near the top of the function when `qty < fill_min_`.  You now return (0,0) for that case.  The only way we can get to this point in `GetFillMass()` is if `qty >= fill_min_`.  Therefore, we can guarantee that `fill_mass >= fill_min_` at this point and that `num_at_fill_mass` is well-behaved.

File: src/toolkit/matl_sell_policy.cc [hunk 2]
```diff
@@ -197,9 +199,12 @@ std::set<BidPortfolio<Material>::Ptr> MatlSellPolicy::GetMatlBids(
     for (rit = requests.begin(); rit != requests.end(); ++rit) {
       req = *rit;
       qty = std::min(req->target()->quantity(), limit);
-      bid_qty = excl ? quantize_ : package_->GetFillMass(qty);
+      std::pair<double, int> fill = package_->GetFillMass(qty);
+      bid_qty = excl ? quantize_ : fill.first;
       if (bid_qty != 0) {
-        n_full_bids = static_cast<int>(std::floor(qty / bid_qty));
+        std::cerr << "bid_qty: " << bid_qty << std::endl;
+        std::cerr << "full bids: " << fill.second << std::endl;
```
Comment (gonuke) [inline src/toolkit/matl_sell_policy.cc:206]: I don't think we need these anymore

**Review by gonuke — CHANGES_REQUESTED** [review]
I thought through the test we moved more carefully and I think this changes removes the need for the test at all.

File: src/toolkit/matl_sell_policy.cc (hunk 2 above)
Comment (nuclearkatie) [reply src/toolkit/matl_sell_policy.cc:206]: Oops

File: src/toolkit/matl_sell_policy.cc [hunk 3]
```diff
@@ -280,6 +283,9 @@ void MatlSellPolicy::GetMatlTrades(
           // packaging successful
           trade_mat = mat_pkgd[0];
           shippable_pkgs-=1;
+        } else {
+          // packaging failed. Will need to ship empty trade
+          trade_mat = Material::CreateUntracked(0, mat->comp());
```
Comment (gonuke) [inline src/toolkit/matl_sell_policy.cc:288]: is there a test for this case?

**Review by gonuke — COMMENTED** [review]
Wondering about another tests for the failed trade?

**Comment by gonuke** [comment]
Rebase on #1796 to pass tests

**Comment by nuclearkatie** [comment]
Cycamore build fails because this PR changes `GetFillMass` from returning a double to returning a pair (double and int). [cycamore#621](https://github.com/cyclus/cycamore/pull/621) fixes that, after this is merged

**Review by gonuke — APPROVED** [review]
